HOMING = 'G28'
APPLY_ACCELERATIONS_AND_VELOCITIES = ''

# POSITIONS
FIRST_POSITION_AFTER_HOMING = ''
SEQUENCE_POSITIONS_BEFORE_CATCH_TUBE = ['', '']
CATCH_TUBE_POSITION = ''
SEQUENCE_POSITIONS_AFTER_CATCH_TUBE = ['', '']
CATCH_COVER_POSITION = ''
SEQUENCE_POSITIONS_AFTER_CATCH_COVER = ['', '']
CLOSE_COVER_POSITION = ''
SEQUENCE_POSITIONS_AFTER_CLOSE_COVER = ['', '']
UNLOAD_TUBE_ARM_POSITION = ''

# SERVOS
OPEN_TUBE_SERVO = ''
CLOSE_TUBE_SERVO = ''
LOAD_TUBE_ARM_SERVO = ''
UNLOAD_TUBE_ARM_SERVO = ''

# TOOL CHANGE
ACTIVATE_POMP_MOTOR = 'T0'
ACTIVATE_COVER_MOTOR = 'T1'


def wait_g_code(ms_delay):
    return 'G4 P' + ms_delay
